main: aliuly\manyworlds\Main
api: [3.0.0]
load: POSTWORLD

name: ManyWorlds
description: Manage Multiple Worlds
version: 2.2.0
author: aliuly

commands:
  manyworlds:
    description: Manage Worlds
    usage: "/mw <help|sub-cmd> [options]"
    permission: mw.cmds
    aliases: [mw]

permissions:
  mw.cmds:
    default: true
    description: ""
  mw.cmd.tp:
    default: op
    description: ""
  mw.cmd.tp.others:
    default: op
    description: ""
  mw.cmd.ls:
    default: op
    description: ""
  mw.cmd.world.create:
    default: op
    description: ""
  mw.cmd.world.load:
    default: op
    description: ""
  mw.cmd.lvdat:
    default: op
    description: ""
  mw.cmd.default:
    default: op
    description: ""
